# Generated by Django 5.2.8 on 2025-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
