# Generated by Django 5.2.8 on 2025-11-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_typemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.typemodel'),
            preserve_default=False,
        ),
    ]
